package com.example.akimchukdaniel.findmypuppy;

import android.provider.BaseColumns;

import com.google.android.gms.maps.model.LatLng;

/**
 * Created by akimchukdaniel on 12/1/16.
 * A model for LostPuppies. Contains an inner class which contains constants for the database.
 */

public class LostPuppy {

    private String name;
    private String breed;
    private String fur;
    private LatLng location;
    private java.util.Date date;
    private String sex;
    private String eye;
    private int id;
    private String lostfound;
    private String phone;
    private String reporter;

    private LostPuppy() {

    }

    /**
     * Constructor for LostPuppy
     * @param id puppy's ID (generated by the database)
     * @param name puppy's name
     * @param breed puppy's breed
     * @param fur puppy's fur color
     * @param location the puppy's last known location
     * @param date the last date the puppy was seen
     * @param sex the puppy's sex
     * @param eye the puppy's eye color
     * @param lostfound "lost" if the puppy was in a lost report, "found" if the puppy was in a found report
     * @param phone phone number of the reporter
     * @param reporter the reporter's name
     */
    public LostPuppy(int id, String name, String breed, String fur, LatLng location, java.util.Date date, String sex, String eye, String lostfound,
                        String phone, String reporter) {
        this.id = id;
        this.name = name;
        this.breed = breed;
        this.fur = fur;
        this.location = location;
        this.date = date;
        this.sex = sex;
        this.eye = eye;
        this.lostfound = lostfound;
        this.phone = phone;
        this.reporter = reporter;
    }

    //GETTERS
    public int getId() {return id;}
    public String getName() {return name;}
    public String getBreed() {return breed;}
    public String getFur() {return fur;}
    public LatLng getLocation() {return location;}
    public java.util.Date getDate() {return date;}
    public String getSex() {return sex;}
    public String getEye() {return eye;}
    public String getLostfound() {return lostfound;}
    public String getPhone() {return phone;}
    public String getReporter() {return reporter;}

    /**
     * static class full of constants for use with the database.
     */
    public static class LostPuppyEntry implements BaseColumns {
        public static final String TABLE_NAME = "lost_puppies";
        public static final String COLUMN_NAME_NAME= "name";
        public static final String COLUMN_NAME_BREED= "breed";
        public static final String COLUMN_NAME_FUR_COLOR= "fur_color";
        public static final String COLUMN_NAME_LAST_LOCATION= "last_seen_location";
        public static final String COLUMN_NAME_LAST_TIME= "last_seen_time";
        public static final String COLUMN_NAME_SEX= "sex";
        public static final String COLUMN_NAME_EYE= "eye_color";
        public static final String COLUMN_NAME_LOSTFOUND= "lostfound";
        public static final String COLUMN_NAME_REPORTER= "reporter";
        public static final String COLUMN_NAME_PHONE= "phone";
    }

    /**
     * Used for the list view and searching
     * @return a string representation the puppy
     */
    public String toString() {
        return lostfound + ": " + name + ", " + fur + " " + breed + ", " + sex;
    }
}
